package streetlight.server.db.tables

val LocationColumns = listOf(
    LocationTable.id,
    LocationTable.cityId,
    LocationTable.mapId,
    LocationTable.slug,
    LocationTable.name,
    LocationTable.description,
    LocationTable.address,
    LocationTable.city,
    LocationTable.state,
    LocationTable.geoPoint,
    LocationTable.mapRank,
    LocationTable.mapCategory,
    LocationTable.mapType,
    LocationTable.resources,
    LocationTable.website,
    LocationTable.eventsUrl,
    LocationTable.menuUrl,
    LocationTable.aboutUrl,
    LocationTable.imageRef,
    LocationTable.images,
    LocationTable.links,
    LocationTable.starCount,
    LocationTable.updatedAt,
    LocationTable.createdAt,
    LocationStarTable.starId,
)