CREATE TABLE IF NOT EXISTS country (id SERIAL PRIMARY KEY, "name" TEXT NOT NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL);
ALTER TABLE country ADD CONSTRAINT country_name_unique UNIQUE ("name");
CREATE TABLE IF NOT EXISTS "state" (id SERIAL PRIMARY KEY, "name" TEXT NOT NULL, country_id INT NOT NULL, country TEXT NOT NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_state_country_id__id FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
ALTER TABLE "state" ADD CONSTRAINT state_name_country_id_unique UNIQUE ("name", country_id);
CREATE TABLE IF NOT EXISTS city (id SERIAL PRIMARY KEY, state_id INT NOT NULL, slug TEXT NOT NULL, "name" TEXT NOT NULL, aliases TEXT[] DEFAULT ARRAY[]::text[] NOT NULL, galaxy_count INT DEFAULT 0 NOT NULL, "state" TEXT NOT NULL, country TEXT NOT NULL, geo_point POINT NULL, geo_bounds DOUBLE PRECISION[] NOT NULL, map_rank REAL NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_city_state_id__id FOREIGN KEY (state_id) REFERENCES "state"(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX city_state_id ON city (state_id);
CREATE INDEX city_slug ON city (slug);
ALTER TABLE city ADD CONSTRAINT city_name_state_id_unique UNIQUE ("name", state_id);
CREATE TABLE IF NOT EXISTS star (id uuid PRIMARY KEY, city_id INT NULL, username TEXT NOT NULL, hashed_password TEXT NULL, disabled_password_hash TEXT NULL, email TEXT NULL, roles INT[] NOT NULL, "name" TEXT NULL, tagline TEXT NULL, description TEXT NULL, identity_visibility INT DEFAULT 0 NOT NULL, account_type INT NOT NULL, email_status INT NULL, scout_level INT DEFAULT 0 NOT NULL, image JSONB NULL, design JSONB NULL, guest_token CHAR(64) NULL, active_at TIMESTAMP DEFAULT '2026-09-15 14:20:02.559'::timestamp without time zone NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, CONSTRAINT fk_star_city_id__id FOREIGN KEY (city_id) REFERENCES city(id) ON DELETE SET NULL ON UPDATE RESTRICT);
CREATE INDEX star_city_id ON star (city_id);
ALTER TABLE star ADD CONSTRAINT star_username_unique UNIQUE (username);
ALTER TABLE star ADD CONSTRAINT star_email_unique UNIQUE (email);
ALTER TABLE star ADD CONSTRAINT star_guest_token_unique UNIQUE (guest_token);
CREATE TABLE IF NOT EXISTS "location" (id uuid PRIMARY KEY, host_id uuid NULL, scout_id uuid NULL, city_id INT NULL, "map_Id" BIGINT NULL, timezone_id TEXT DEFAULT 'America/Denver' NOT NULL, slug TEXT NOT NULL, past_slug TEXT NULL, host TEXT NULL, scout TEXT NULL, "name" TEXT NULL, description TEXT NULL, address TEXT NULL, city TEXT NULL, "state" TEXT NULL, geo_point POINT NULL, map_rank REAL NULL, map_category TEXT NULL, map_type TEXT NULL, resources INT[] NOT NULL, hours JSONB NULL, parse_mode INT DEFAULT 1 NOT NULL, design JSONB NULL, link TEXT NULL, star_count INT DEFAULT 0 NOT NULL, links JSONB NULL, events_url TEXT NULL, image JSONB NULL, checked_at TIMESTAMP NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_location_host_id__id FOREIGN KEY (host_id) REFERENCES star(id) ON DELETE SET NULL ON UPDATE RESTRICT, CONSTRAINT fk_location_scout_id__id FOREIGN KEY (scout_id) REFERENCES star(id) ON DELETE SET NULL ON UPDATE RESTRICT, CONSTRAINT fk_location_city_id__id FOREIGN KEY (city_id) REFERENCES city(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
ALTER TABLE "location" ADD CONSTRAINT location_map_id_unique UNIQUE ("map_Id");
ALTER TABLE "location" ADD CONSTRAINT location_slug_unique UNIQUE (slug);
CREATE INDEX location_past_slug ON "location" (past_slug);
CREATE INDEX location_host ON "location" (host);
CREATE INDEX location_scout ON "location" (scout);
CREATE TABLE IF NOT EXISTS song (id uuid PRIMARY KEY, star_id uuid NOT NULL, title TEXT NOT NULL, artist TEXT NOT NULL, notation JSONB NULL, tempo INT NULL, capo INT NULL, in_rotation BOOLEAN DEFAULT TRUE NOT NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_song_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS request (id uuid PRIMARY KEY, event_id uuid NOT NULL, song_id uuid NOT NULL, is_joining BOOLEAN NOT NULL, "comment" TEXT NULL, requester_name TEXT NULL, created_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS "event" (id uuid PRIMARY KEY, scout_id uuid NULL, location_id uuid NOT NULL, current_song_id uuid NULL, slug TEXT NOT NULL, past_slug TEXT NULL, scout TEXT DEFAULT '' NOT NULL, location_slug TEXT DEFAULT '' NOT NULL, title TEXT NOT NULL, description TEXT NULL, status INT NOT NULL, contact TEXT NULL, age_min INT NULL, "cost" REAL NULL, visibility INT NULL, links JSONB NULL, url TEXT NULL, image JSONB NULL, stream_url TEXT NULL, time_zone_id TEXT NOT NULL, star_count INT DEFAULT 0 NOT NULL, starts_at TIMESTAMP NULL, ends_at TIMESTAMP NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL);
ALTER TABLE "event" ADD CONSTRAINT event_slug_unique UNIQUE (slug);
CREATE INDEX event_past_slug ON "event" (past_slug);
CREATE INDEX event_scout ON "event" (scout);
CREATE INDEX event_location_slug ON "event" (location_slug);
CREATE TABLE IF NOT EXISTS rendition (id uuid PRIMARY KEY, song_id uuid NOT NULL, star_id uuid NOT NULL, notes TEXT NULL, rating INT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_rendition_song_id__id FOREIGN KEY (song_id) REFERENCES song(id) ON DELETE CASCADE ON UPDATE RESTRICT, CONSTRAINT fk_rendition_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS "session" (id uuid PRIMARY KEY, star_id uuid NOT NULL, token_hash CHAR(64) NOT NULL, ttl INT NOT NULL, created_at TIMESTAMP NOT NULL, expires_at TIMESTAMP NOT NULL, CONSTRAINT fk_session_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX session_star_id ON "session" (star_id);
ALTER TABLE "session" ADD CONSTRAINT session_token_hash_unique UNIQUE (token_hash);
CREATE TABLE IF NOT EXISTS performer (id uuid PRIMARY KEY, star_id uuid NOT NULL, venmo TEXT NOT NULL, stage_name TEXT NOT NULL, CONSTRAINT fk_performer_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS transit_route (id TEXT PRIMARY KEY, short_name TEXT NOT NULL, long_name TEXT NOT NULL, description TEXT NULL, vehicle_type INT NULL, points JSON NOT NULL);
CREATE TABLE IF NOT EXISTS transit_stop (id TEXT PRIMARY KEY, "name" TEXT NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, description TEXT NULL);
CREATE TABLE IF NOT EXISTS transit_route_stop (transit_route_id TEXT, transit_stop_id TEXT, CONSTRAINT pk_transit_route_stop PRIMARY KEY (transit_route_id, transit_stop_id), CONSTRAINT fk_transit_route_stop_transit_route_id__id FOREIGN KEY (transit_route_id) REFERENCES transit_route(id) ON DELETE CASCADE ON UPDATE RESTRICT, CONSTRAINT fk_transit_route_stop_transit_stop_id__id FOREIGN KEY (transit_stop_id) REFERENCES transit_stop(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS event_tag (id TEXT PRIMARY KEY, "name" TEXT NOT NULL, description TEXT NULL);
CREATE TABLE IF NOT EXISTS image (id uuid PRIMARY KEY, star_id uuid NULL, url TEXT NULL, format INT NOT NULL, "name" TEXT NULL, aspect REAL NOT NULL, description TEXT NULL, attribution TEXT NULL, "attributionUrl" TEXT NULL, string TEXT NULL, variants JSONB NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_image_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS talent (id uuid PRIMARY KEY, star_id uuid NOT NULL, "name" TEXT NOT NULL, description TEXT NULL, image_url TEXT NULL, experience INT NOT NULL, talent_type INT NOT NULL, talent_level INT NOT NULL, year_started INT NOT NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_talent_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS galaxy (id uuid PRIMARY KEY, star_id uuid NULL, city_id INT NULL, city TEXT NULL, "path" TEXT NOT NULL, past_slug TEXT NULL, "name" TEXT NOT NULL, tagline TEXT NULL, description TEXT NULL, geo_point POINT NULL, geo_bounds DOUBLE PRECISION[] NOT NULL, post_permission INT NOT NULL, review_count INT DEFAULT 0 NOT NULL, post_guide TEXT NULL, image JSONB NULL, design JSONB NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, star_count INT DEFAULT 0 NOT NULL, event_count INT DEFAULT 0 NOT NULL, location_count INT DEFAULT 0 NOT NULL, post_count INT DEFAULT 0 NOT NULL, CONSTRAINT fk_galaxy_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE SET NULL ON UPDATE RESTRICT, CONSTRAINT fk_galaxy_city_id__id FOREIGN KEY (city_id) REFERENCES city(id) ON DELETE SET NULL ON UPDATE RESTRICT);
ALTER TABLE galaxy ADD CONSTRAINT galaxy_path_unique UNIQUE ("path");
CREATE INDEX galaxy_past_slug ON galaxy (past_slug);
CREATE TABLE IF NOT EXISTS galaxy_host (galaxy_id uuid, host_id uuid, host_type INT NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT pk_galaxy_host PRIMARY KEY (galaxy_id, host_id), CONSTRAINT fk_galaxy_host_galaxy_id__id FOREIGN KEY (galaxy_id) REFERENCES galaxy(id) ON DELETE CASCADE ON UPDATE RESTRICT, CONSTRAINT fk_galaxy_host_host_id__id FOREIGN KEY (host_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX galaxy_host_galaxy_id ON galaxy_host (galaxy_id);
CREATE INDEX galaxy_host_host_id ON galaxy_host (host_id);
CREATE TABLE IF NOT EXISTS "comment" (id uuid PRIMARY KEY, parent_id uuid NULL, star_id uuid NULL, "text" TEXT NOT NULL, star_count INT DEFAULT 0 NOT NULL, reply_count INT DEFAULT 0 NOT NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE INDEX comment_parent_id ON "comment" (parent_id);
CREATE INDEX comment_star_id ON "comment" (star_id);
CREATE INDEX comment_created_at ON "comment" (created_at);
CREATE TABLE IF NOT EXISTS galaxy_comment (galaxy_id uuid, comment_id uuid, CONSTRAINT pk_galaxy_comment PRIMARY KEY (galaxy_id, comment_id));
CREATE INDEX galaxy_comment_galaxy_id ON galaxy_comment (galaxy_id);
CREATE INDEX galaxy_comment_comment_id ON galaxy_comment (comment_id);
CREATE TABLE IF NOT EXISTS galaxy_star (galaxy_id uuid, star_id uuid, created_at TIMESTAMP NOT NULL, CONSTRAINT pk_galaxy_star PRIMARY KEY (galaxy_id, star_id), CONSTRAINT fk_galaxy_star_galaxy_id__id FOREIGN KEY (galaxy_id) REFERENCES galaxy(id) ON DELETE CASCADE ON UPDATE RESTRICT, CONSTRAINT fk_galaxy_star_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX galaxy_star_galaxy_id ON galaxy_star (galaxy_id);
CREATE INDEX galaxy_star_star_id ON galaxy_star (star_id);
CREATE TABLE IF NOT EXISTS media (id uuid PRIMARY KEY, star_id uuid NOT NULL, slug TEXT NOT NULL, username TEXT NOT NULL, media_type INT NOT NULL, title TEXT NULL, subtitle TEXT NULL, "text" TEXT NULL, link TEXT NULL, geo_point POINT NULL, image JSONB NULL, design JSONB NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_media_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX media_slug ON media (slug);
CREATE INDEX media_username ON media (username);
CREATE TABLE IF NOT EXISTS post (id uuid PRIMARY KEY, galaxy_id uuid NOT NULL, user_id uuid NULL, event_id uuid NULL, location_id uuid NULL, media_id uuid NULL, title TEXT NULL, username TEXT NULL, "text" TEXT NULL, post_type INT NOT NULL, status INT DEFAULT 1 NOT NULL, lean INT DEFAULT 0 NOT NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, galaxy_slug TEXT NULL, galaxy_name TEXT NULL, star_count INT DEFAULT 0 NOT NULL);
CREATE INDEX post_galaxy_id ON post (galaxy_id);
CREATE INDEX post_user_id ON post (user_id);
CREATE INDEX post_event_id ON post (event_id);
CREATE INDEX post_location_id ON post (location_id);
CREATE INDEX post_media_id ON post (media_id);
CREATE INDEX post_title ON post (title);
CREATE INDEX post_updated_at ON post (updated_at);
CREATE INDEX post_created_at ON post (created_at);
CREATE INDEX post_star_count ON post (star_count);
CREATE TABLE IF NOT EXISTS comment_star (star_id uuid, comment_id uuid, CONSTRAINT pk_comment_star PRIMARY KEY (star_id, comment_id));
CREATE INDEX comment_star_star_id ON comment_star (star_id);
CREATE INDEX comment_star_comment_id ON comment_star (comment_id);
CREATE TABLE IF NOT EXISTS media_comment (media_id uuid, comment_id uuid, CONSTRAINT pk_media_comment PRIMARY KEY (media_id, comment_id));
CREATE INDEX media_comment_media_id ON media_comment (media_id);
CREATE INDEX media_comment_comment_id ON media_comment (comment_id);
CREATE TABLE IF NOT EXISTS event_star (event_id uuid, star_id uuid, created_at TIMESTAMP NOT NULL, CONSTRAINT pk_event_star PRIMARY KEY (event_id, star_id));
CREATE INDEX event_star_event_id ON event_star (event_id);
CREATE INDEX event_star_star_id ON event_star (star_id);
CREATE TABLE IF NOT EXISTS location_star (location_id uuid, star_id uuid, created_at TIMESTAMP NOT NULL, CONSTRAINT pk_location_star PRIMARY KEY (location_id, star_id), CONSTRAINT fk_location_star_location_id__id FOREIGN KEY (location_id) REFERENCES "location"(id) ON DELETE CASCADE ON UPDATE RESTRICT, CONSTRAINT fk_location_star_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX location_star_location_id ON location_star (location_id);
CREATE INDEX location_star_star_id ON location_star (star_id);
CREATE TABLE IF NOT EXISTS omni (id uuid PRIMARY KEY, record JSONB NOT NULL, record_at TIMESTAMP NOT NULL);
CREATE INDEX omni_record_at ON omni (record_at);
CREATE TABLE IF NOT EXISTS edit_log (id uuid PRIMARY KEY, record_id uuid NOT NULL, star_id uuid NULL, username TEXT DEFAULT '' NOT NULL, record_type INT NOT NULL, record_edit JSONB NULL, edit_type INT NOT NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_edit_log_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE SET NULL ON UPDATE RESTRICT);
CREATE INDEX edit_log_star_id ON edit_log (star_id);
CREATE INDEX edit_log_username ON edit_log (username);
CREATE TABLE IF NOT EXISTS task (id uuid PRIMARY KEY, star_id uuid NOT NULL, record_id uuid NOT NULL, record_type INT NOT NULL, status INT NOT NULL, decision INT NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_task_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX task_star_id ON task (star_id);
CREATE INDEX task_record_id ON task (record_id);
CREATE TABLE IF NOT EXISTS feedback (id uuid PRIMARY KEY, star_id uuid NULL, username TEXT NULL, "text" TEXT NOT NULL, feedback_type INT NOT NULL, platform INT NOT NULL, is_private BOOLEAN NOT NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_feedback_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE SET NULL ON UPDATE RESTRICT);
CREATE INDEX feedback_star_id ON feedback (star_id);
CREATE TABLE IF NOT EXISTS quorum (id uuid PRIMARY KEY, record_id uuid NOT NULL, record_type INT NOT NULL, question INT NOT NULL, decision INT NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE INDEX quorum_record_id ON quorum (record_id);
CREATE TABLE IF NOT EXISTS "policy" (id uuid PRIMARY KEY, policy_scope INT NOT NULL, policy_type INT NOT NULL, policy_target INT NOT NULL, "label" TEXT NOT NULL, definition TEXT NOT NULL, is_default BOOLEAN NOT NULL, is_reportable BOOLEAN NOT NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS flag (id uuid PRIMARY KEY, flagger_id uuid NOT NULL, policy_id uuid NULL, record_id uuid NOT NULL, record_type INT NOT NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_flag_flagger_id__id FOREIGN KEY (flagger_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT, CONSTRAINT fk_flag_policy_id__id FOREIGN KEY (policy_id) REFERENCES "policy"(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX flag_flagger_id ON flag (flagger_id);
CREATE INDEX flag_policy_id ON flag (policy_id);
CREATE INDEX flag_record_id ON flag (record_id);
CREATE TABLE IF NOT EXISTS site_status (id BIGSERIAL PRIMARY KEY, integers JSONB NOT NULL, doubles JSONB NOT NULL, resolution INT NOT NULL, coverage REAL NOT NULL, started_at TIMESTAMP NOT NULL, ended_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS auth_token (id BIGSERIAL PRIMARY KEY, star_id uuid NOT NULL, hashed_token CHAR(64) NOT NULL, auth_type INT NOT NULL, email TEXT NOT NULL, consumed_at TIMESTAMP NULL, expires_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_auth_token_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT);
ALTER TABLE auth_token ADD CONSTRAINT auth_token_hashed_token_unique UNIQUE (hashed_token);
CREATE TABLE IF NOT EXISTS bounced_email (id BIGSERIAL PRIMARY KEY, email TEXT NOT NULL, reason TEXT NULL, bounced_at TIMESTAMP NOT NULL);
ALTER TABLE bounced_email ADD CONSTRAINT bounced_email_email_unique UNIQUE (email);
CREATE TABLE IF NOT EXISTS origin (origin_id VARCHAR(253) PRIMARY KEY, robots_txt TEXT NULL, fetch_mode INT DEFAULT 0 NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS "parser" (id uuid PRIMARY KEY, origin_id VARCHAR(253) NOT NULL, schema_type INT NOT NULL, fetch_mode INT DEFAULT 0 NOT NULL, "schema" JSONB NOT NULL, consecutive_fail_count INT DEFAULT 0 NOT NULL, last_success_at TIMESTAMP NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_parser_origin_id__origin_id FOREIGN KEY (origin_id) REFERENCES origin(origin_id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX parser_origin_id ON "parser" (origin_id);
CREATE TABLE IF NOT EXISTS location_origin (location_id uuid, origin_id VARCHAR(253), CONSTRAINT pk_location_origin PRIMARY KEY (location_id, origin_id), CONSTRAINT fk_location_origin_location_id__id FOREIGN KEY (location_id) REFERENCES "location"(id) ON DELETE CASCADE ON UPDATE RESTRICT, CONSTRAINT fk_location_origin_origin_id__origin_id FOREIGN KEY (origin_id) REFERENCES origin(origin_id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX location_origin_location_id ON location_origin (location_id);
CREATE INDEX location_origin_origin_id ON location_origin (origin_id);
CREATE TABLE IF NOT EXISTS link (id uuid PRIMARY KEY, origin_id VARCHAR(253) NOT NULL, url TEXT NOT NULL, schema_type INT NULL, fetched_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_link_origin_id__origin_id FOREIGN KEY (origin_id) REFERENCES origin(origin_id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX link_origin_id ON link (origin_id);
ALTER TABLE link ADD CONSTRAINT link_url_unique UNIQUE (url);
CREATE TABLE IF NOT EXISTS link_alias (id uuid PRIMARY KEY, link_id uuid NOT NULL, url TEXT NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_link_alias_link_id__id FOREIGN KEY (link_id) REFERENCES link(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX link_alias_link_id ON link_alias (link_id);
ALTER TABLE link_alias ADD CONSTRAINT link_alias_url_unique UNIQUE (url);
CREATE TABLE IF NOT EXISTS subdomain (id uuid PRIMARY KEY, slug TEXT NOT NULL, location_id uuid NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_subdomain_location_id__id FOREIGN KEY (location_id) REFERENCES "location"(id) ON DELETE CASCADE ON UPDATE RESTRICT);
ALTER TABLE subdomain ADD CONSTRAINT subdomain_slug_unique UNIQUE (slug);
ALTER TABLE subdomain ADD CONSTRAINT subdomain_location_id_unique UNIQUE (location_id);
CREATE TABLE IF NOT EXISTS chat (id uuid PRIMARY KEY, last_message_id uuid NULL, subject TEXT NULL, last_message_preview TEXT NOT NULL, last_message_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS message (id uuid PRIMARY KEY, chat_id uuid NOT NULL, star_id uuid NULL, "content" TEXT NOT NULL, sent_at TIMESTAMP NOT NULL);
CREATE INDEX message_star_id ON message (star_id);
CREATE INDEX message_sent_at ON message (sent_at);
CREATE INDEX message_chat_sent ON message (chat_id, sent_at);
CREATE TABLE IF NOT EXISTS chat_star (chat_id uuid, star_id uuid, last_read_at TIMESTAMP NULL, archived_at TIMESTAMP NULL, CONSTRAINT pk_chat_star PRIMARY KEY (star_id, chat_id));
CREATE INDEX chat_star_star_id ON chat_star (star_id);
CREATE TABLE IF NOT EXISTS galaxy_mark (id uuid PRIMARY KEY, galaxy_id uuid NOT NULL, "name" TEXT NOT NULL, lean INT NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_galaxy_mark_galaxy_id__id FOREIGN KEY (galaxy_id) REFERENCES galaxy(id) ON DELETE CASCADE ON UPDATE RESTRICT);
CREATE INDEX galaxy_mark_galaxy_id ON galaxy_mark (galaxy_id);
ALTER TABLE galaxy_mark ADD CONSTRAINT galaxy_mark_galaxy_id_name_unique UNIQUE (galaxy_id, "name");
CREATE TABLE IF NOT EXISTS post_mark (post_id uuid, star_id uuid, galaxy_mark_id uuid, created_at TIMESTAMP NOT NULL, CONSTRAINT pk_post_mark PRIMARY KEY (post_id, star_id, galaxy_mark_id));
CREATE INDEX post_mark_post_id ON post_mark (post_id);
CREATE INDEX post_mark_star_id ON post_mark (star_id);
CREATE TABLE IF NOT EXISTS post_mark_count (post_id uuid, galaxy_mark_id uuid, "count" INT DEFAULT 0 NOT NULL, CONSTRAINT pk_post_mark_count PRIMARY KEY (post_id, galaxy_mark_id));
CREATE INDEX post_mark_count_galaxy_mark_id_count_post_id ON post_mark_count (galaxy_mark_id, "count", post_id);
ALTER TABLE request ADD CONSTRAINT fk_request_event_id__id FOREIGN KEY (event_id) REFERENCES "event"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE request ADD CONSTRAINT fk_request_song_id__id FOREIGN KEY (song_id) REFERENCES song(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "event" ADD CONSTRAINT fk_event_scout_id__id FOREIGN KEY (scout_id) REFERENCES star(id) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE "event" ADD CONSTRAINT fk_event_location_id__id FOREIGN KEY (location_id) REFERENCES "location"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE "event" ADD CONSTRAINT fk_event_current_song_id__id FOREIGN KEY (current_song_id) REFERENCES request(id) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE "comment" ADD CONSTRAINT fk_comment_parent_id__id FOREIGN KEY (parent_id) REFERENCES "comment"(id) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE "comment" ADD CONSTRAINT fk_comment_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE galaxy_comment ADD CONSTRAINT fk_galaxy_comment_galaxy_id__id FOREIGN KEY (galaxy_id) REFERENCES galaxy(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE galaxy_comment ADD CONSTRAINT fk_galaxy_comment_comment_id__id FOREIGN KEY (comment_id) REFERENCES "comment"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE post ADD CONSTRAINT fk_post_galaxy_id__id FOREIGN KEY (galaxy_id) REFERENCES galaxy(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE post ADD CONSTRAINT fk_post_user_id__id FOREIGN KEY (user_id) REFERENCES star(id) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE post ADD CONSTRAINT fk_post_event_id__id FOREIGN KEY (event_id) REFERENCES "event"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE post ADD CONSTRAINT fk_post_location_id__id FOREIGN KEY (location_id) REFERENCES "location"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE post ADD CONSTRAINT fk_post_media_id__id FOREIGN KEY (media_id) REFERENCES media(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE comment_star ADD CONSTRAINT fk_comment_star_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE comment_star ADD CONSTRAINT fk_comment_star_comment_id__id FOREIGN KEY (comment_id) REFERENCES "comment"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE media_comment ADD CONSTRAINT fk_media_comment_media_id__id FOREIGN KEY (media_id) REFERENCES media(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE media_comment ADD CONSTRAINT fk_media_comment_comment_id__id FOREIGN KEY (comment_id) REFERENCES "comment"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE event_star ADD CONSTRAINT fk_event_star_event_id__id FOREIGN KEY (event_id) REFERENCES "event"(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE event_star ADD CONSTRAINT fk_event_star_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE chat ADD CONSTRAINT fk_chat_last_message_id__id FOREIGN KEY (last_message_id) REFERENCES message(id) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE message ADD CONSTRAINT fk_message_chat_id__id FOREIGN KEY (chat_id) REFERENCES chat(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE message ADD CONSTRAINT fk_message_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE SET NULL ON UPDATE RESTRICT;
ALTER TABLE chat_star ADD CONSTRAINT fk_chat_star_chat_id__id FOREIGN KEY (chat_id) REFERENCES chat(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE chat_star ADD CONSTRAINT fk_chat_star_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE post_mark ADD CONSTRAINT fk_post_mark_post_id__id FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE post_mark ADD CONSTRAINT fk_post_mark_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE post_mark ADD CONSTRAINT fk_post_mark_galaxy_mark_id__id FOREIGN KEY (galaxy_mark_id) REFERENCES galaxy_mark(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE post_mark_count ADD CONSTRAINT fk_post_mark_count_post_id__id FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE post_mark_count ADD CONSTRAINT fk_post_mark_count_galaxy_mark_id__id FOREIGN KEY (galaxy_mark_id) REFERENCES galaxy_mark(id) ON DELETE CASCADE ON UPDATE RESTRICT;
CREATE SEQUENCE IF NOT EXISTS city_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS country_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS state_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS site_status_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS auth_token_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS bounced_email_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
