CREATE TABLE IF NOT EXISTS bug (id uuid PRIMARY KEY, star_id uuid NULL, build_id TEXT NULL, screen INT NULL, "path" TEXT NULL, description TEXT NOT NULL, platform INT NOT NULL, device_agent TEXT NULL, status INT NOT NULL, updated_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_bug_star_id__id FOREIGN KEY (star_id) REFERENCES star(id) ON DELETE SET NULL ON UPDATE RESTRICT);
CREATE INDEX IF NOT EXISTS bug_star_id ON bug (star_id);
CREATE TABLE IF NOT EXISTS site_event (id uuid DEFAULT gen_random_uuid() PRIMARY KEY, "label" TEXT NOT NULL, "time" TIMESTAMP NOT NULL);
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS device_agent TEXT NULL;
ALTER TABLE star ADD COLUMN IF NOT EXISTS stripe_id TEXT NULL;
ALTER TABLE star ADD COLUMN IF NOT EXISTS venmo_id TEXT NULL;
ALTER TABLE star ADD COLUMN IF NOT EXISTS paypal_id TEXT NULL;
ALTER TABLE star ADD COLUMN IF NOT EXISTS cashapp_id TEXT NULL;
