package streetlight.server.routes

//language="MD"
object SchemaParserText {

    val contentObjectInstructions = """
The parent object has two parameters:

* isExpectedContent: true if the document contains the expected content, false if it does not
* content: an object with the parameters described below. Null if the document does not contain the expected content.
"""

    val SelectorPreferenceInstructions = """
Prefer selectors whose names describe the content they hold (e.g. ".event-title", ".venue-name",
"[itemprop=startDate]") over selectors whose names describe layout or position
(e.g. ".et_pb_text_1_tb_body", ".column-2", ".css-1a2b3c"). A name that refers to the property
you are extracting will keep its meaning if the page is redesigned; a name generated by a page
builder refers only to where an element currently sits, and may mean something different on
another page of the same site.

In order of preference:
1. Attributes authored for machines: [itemprop], [itemtype], [data-*] naming the content.
2. Class or id names that describe the content.
3. Semantic elements and heading levels, alone or anchored to a content-named ancestor
   (e.g. ".event-details time", "article h1").
4. Layout or builder-generated class names, when nothing above is available.
5. A descendant chain of tags, as a last resort.

A selector from group 4 or 5 is acceptable when it is the only option, but do not choose one
over an option from an earlier group merely because it is shorter.

Given those considerations, the selector values you provide should be the minimal selector necessary to return the desired elements.

The selectors should not specifically target elements within the head.
"""

    val EventFeedSelectorsInstructions = """
Read the following HTML. We believe it is a calendar page or feed with a listing of events at a particular location.
Your role is to extract a set of CSS selectors that can be used to parse the page for event information.
Remember that you are not providing the details themselves, only the selectors that will be used to
query the document. 

$SelectorPreferenceInstructions

The document body will be queried for the event selector, and this is expected to return a list of elements.

Event-specific selectors are queried against each event element and must not repeat the event
selector as a prefix. If the event selector is ".event-item" and the title sits in
"<h3 class='event-title'>", the title selector is ".event-title", not ".event-item .event-title".

Sometimes the event feed will be associated with a particular location or venue, and sometimes it will be a list
of local events like you might find on a social media page or news website. When it is a feed associated with a location,
assign a selector to `feedLocation` that will return an element within the body with textContent that matches the location name. 
When there is information about the event location within the event element, assign that selector to `eventLocation`.

If the content of the document does not contain the information that the selector is intended to query,
leave its value null. A null value in that case is correct and expected.

If any of the selectors must target the event element itself, as you might expect with an anchor that wraps the entire 
event content, define it as a single dot: "." This applies only to selectors queried within event elements.
 
Sometimes the target information will be contained within a set of child elements, that is fine but the
textContent should evaluate to the desired information where relevant.

Each value should be a valid CSS query, except in the case of a single dot that indicates the event element.

$contentObjectInstructions

For the content object, determine the following:

### Selectors that will be queried within the body
* feedLocation: This selector should return a single element within the body with text content that matches the name of the location associated with the feed, if it is a location feed.
    - This should be null if the feed is not associated with a location.
* address: This selector should return a single element within the body with text content that matches the address of the location associated with the feed, if it is a location feed.
* event: This selector will be used to return a list of elements that each contain details about a specific event.

### Selectors that will be queried within event elements
* eventLocation: This selector should return the name of the event location if it is present within the event element.
* title: This selector should return an element with text content that reflects the event title.
* link: This selector should return an anchor element with a href attribute with an absolute or relative address to an event page.
    - It may be the same as title.
    - Unlike the other elements, the information in the href attribute will be used and not the text content.
* image: This selector should return an img element with a src attribute referencing an image for the event.
    - Like link, the src attribute will be used and not the text content.
* cost: This selector should return an element with text content about the cost of an event or whether it is free.
    - This element should display a dollar amount or some other currency. If this information is not present, this value should be null.
* description: This selector should return an element with text content that describes the event.
    - It may contain a variety of elements.
* date: This selector should return an element with text content about the date of the event.
* time: This selector should return an element with text content about the time of the event. 
    - It may be the same as date.
"""

    val EventPageSelectorsInstructions = """
Read the following HTML. We believe it is a page with detailed information about a single event at a particular location.
Your role is to extract a set of CSS selectors that can be used to parse the page for event information.
Remember that you are not providing the details themselves, only the selectors that will be used to
query the document. 

$SelectorPreferenceInstructions

Each selector will be queried against the document body and is expected to return a single element.     
If the content of the document does not contain the information that the selector is intended to query,
leave its value null. A null value in that case is correct and expected. 
 
Sometimes the target information will be contained within a set of child elements, that is fine but the
textContent should evaluate to the desired information where relevant.

Each value should be a valid CSS query.

$contentObjectInstructions

For the content object, determine the following:
* title: This selector should return an element with text content that reflects the event title.
* location: This selector should return an element with text content that matches the name of the location.
* address: This selector should return an element with text content that reflects the address of the location.
* image: This selector should return an img element with a src attribute referencing an image for the event.
    - Unlike the other elements, the information in the src attribute will be used and not the text content.
* cost: This selector should return an element with text content about the cost of an event or whether it is free.
    - This element should display a dollar amount or some other currency. If this information is not present, this value should be null.
* description: This selector should return an element with text content that describes the event.
    - It may contain a variety of elements.
* date: This selector should return an element with text content about the date of the event.
* startTime: This selector should return an element with text content about the time the event begins.
    - It may be the same as date.
* endTime: This selector should return an element with text content about the time the event ends.
    - Only provide this if it is different from startTime.
* ageMin: This selector should return an element with text content about the minimum age required to attend the event.
* contact: This selector should return an element with text content providing an email address, phone number,
    or social media link offered for the express purpose of contacting someone about the event.
"""
}